#!/bin/bash
LIMIT=19 # Upper limit
echo
echo "Numbers 1 through 20 (but not 3 and 11)."
a=0
while [ $a -le "$LIMIT" ]
do
a=$(($a+1))
#Agnohse ta 3, 11
if [ "$a" -eq 3 ] || [ "$a" -eq 11 ] 
then
continue 
fi
echo -n "$a " # Den ekteleitai gia ta 3 and 11.

done

echo

a=0
while [ "$a" -le "$LIMIT" ]
do
a=$(($a+1))
if [ "$a" -gt 2 ]
then
break # Skip entire rest of loop.
fi
echo -n "$a "
done

echo

