#!/bin/bash
#
# Usage: factorial number
#
if [ "$#" -ne 1 ] 
then
echo "Just give 1 argument"
exit 1
fi

if [ "$1" -lt 0 ] 
then
echo Please give positive number
exit 1
fi

fact=1
for ((i = 1; i <= $1; i++))
do
fact=`expr $fact \* $i`
done
echo $fact
